AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  functionality related to the Credible Behavioral Health Software platform
Parameters:
  IsDev:
    Type: String
    Default: 'False'
    AllowedValues:
      - 'False'
      - 'True'
  StorageBucket:
    Type: String
    Description: Location to store extracted Credible data
    Default: algernonsolutions-gentlemen-dev
  LayerArn:
    Type: String
    Description: the lambda layer containing the common dependencies
    Default: 'arn:aws:lambda:us-east-1:726075243133:layer:algLayer:3'
Conditions:
  DevDeploy: !Equals [!Ref IsDev, 'True']
  ProdDeploy: !Equals [!Ref IsDev, 'False']

Resources:
  Task:
    Type: AWS::Serverless::Function
    Properties:
      Handler: toll_booth.tasks.handler
      Role: !ImportValue dev-worker-role-arn
      ReservedConcurrentExecutions: 1
      CodeUri: src/
      Timeout: 600
      Runtime: python3.7
      Tracing: Active
      Environment:
        Variables:
          STORAGE_BUCKET: !Ref StorageBucket
  GetClientsOyster:
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-east-1:726075243133:applications/AlgernonOyster
        SemanticVersion: 0.0.45
      Parameters:
        IsDev: !Ref IsDev
        OysterBedEndpoint: 'mh5syterirdvzji7tdbrrmpe7m.appsync-api.us-east-1.amazonaws.com'
        LambdaRoleArn: 'arn:aws:iam::726075243133:role/worker-leech-dev-2-Oyster-168YECYUUDQMK'
        TaskFunctionArn: !GetAtt Task.Arn
        ReservedConcurrency: 1
        TaskName: "get_client_ids"
  GetClientEncountersOyster:
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-east-1:726075243133:applications/AlgernonOyster
        SemanticVersion: 0.0.45
      Parameters:
        IsDev: !Ref IsDev
        OysterBedEndpoint: 'mh5syterirdvzji7tdbrrmpe7m.appsync-api.us-east-1.amazonaws.com'
        LambdaRoleArn: 'arn:aws:iam::726075243133:role/worker-leech-dev-2-Oyster-168YECYUUDQMK'
        TaskFunctionArn: !GetAtt Task.Arn
        ReservedConcurrency: 1
        TaskName: "get_client_encounter_ids"
  GetClientEncounterOyster:
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-east-1:726075243133:applications/AlgernonOyster
        SemanticVersion: 0.0.45
      Parameters:
        IsDev: !Ref IsDev
        OysterBedEndpoint: 'mh5syterirdvzji7tdbrrmpe7m.appsync-api.us-east-1.amazonaws.com'
        LambdaRoleArn: 'arn:aws:iam::726075243133:role/worker-leech-dev-2-Oyster-168YECYUUDQMK'
        TaskFunctionArn: !GetAtt Task.Arn
        ReservedConcurrency: 1
        TaskName: "get_encounter"

Outputs:
  CredibleFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt Task.Arn
  GetClientsListener:
    Value: !GetAtt GetClientsOyster.Outputs.ShuckLineListener
  GetClientEncountersListener:
    Value: !GetAtt GetClientEncountersOyster.Outputs.ShuckLineListener
  GetClientEncounterListener:
    Value: !GetAtt GetClientEncounterOyster.Outputs.ShuckLineListener