AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  functionality related to the Credible Behavioral Health Software platform

Parameters:
  IsDev:
    Type: String
    Default: 'False'
    AllowedValues:
      - 'False'
      - 'True'
  WorkerRoleArn:
    Type: String
    Description: the role to be used for operations of the module

Conditions:
  DevDeploy: !Equals [!Ref IsDev, 'True']
  ProdDeploy: !Equals [!Ref IsDev, 'False']

Resources:
  GetObjectRange:
    Type: AWS::Serverless::Function
    Properties:
      Handler: toll_booth.query_object_range_h
      Role: !Ref WorkerRoleArn
      ReservedConcurrentExecutions: 1
      CodeUri: src/
      Timeout: 120
      Runtime: python3.7
      Tracing: Active
  ExtractObject:
    Type: AWS::Serverless::Function
    Properties:
      Handler: toll_booth.extract_credible_object_h
      Role: !Ref WorkerRoleArn
      ReservedConcurrentExecutions: 1
      CodeUri: src/
      Timeout: 120
      Runtime: python3.7
      Tracing: Active
  ExtractObjects:
    Type: AWS::Serverless::Function
    Properties:
      Handler: toll_booth.extract_credible_objects_h
      Role: !Ref WorkerRoleArn
      ReservedConcurrentExecutions: 1
      CodeUri: src/
      Timeout: 240
      Runtime: python3.7
      Tracing: Active
  ParseExtractionBatch:
    Type: AWS::Serverless::Function
    Properties:
      Handler: toll_booth.parse_batch_encounters
      Role: !Ref WorkerRoleArn
      ReservedConcurrentExecutions: 1
      CodeUri: src/
      Timeout: 900
      Runtime: python3.7
      Tracing: Active
