AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  functionality related to the Credible Behavioral Health Software platform

Parameters:
  IsDev:
    Type: String
    Default: 'False'
    AllowedValues:
      - 'False'
      - 'True'
  StorageBucket:
    Type: String
    Description: Location to store extracted Credible data
    Default: algernonsolutions-gentlemen-dev
  LeechBucket:
    Type: String
    Description: Name of common bucket used by the application
  AlgernonBucket:
    Type: String
    Description: Name of the bucket used to store cached objects

Conditions:
  DevDeploy: !Equals [!Ref IsDev, 'True']
  ProdDeploy: !Equals [!Ref IsDev, 'False']

Resources:
  GetObjectRange:
    Type: AWS::Serverless::Function
    Properties:
      Handler: toll_booth.query_object_range_h
      Role: !ImportValue dev-worker-role-arn
      ReservedConcurrentExecutions: 1
      CodeUri: src/
      Timeout: 120
      Runtime: python3.7
      Tracing: Active
      Environment:
        Variables:
          STORAGE_BUCKET: !Ref StorageBucket
          LEECH_BUCKET: !Ref LeechBucket
          ALGERNON_BUCKET_NAME: !Ref AlgernonBucket
  ExtractObject:
    Type: AWS::Serverless::Function
    Properties:
      Handler: toll_booth.extract_credible_object_h
      Role: !ImportValue dev-worker-role-arn
      ReservedConcurrentExecutions: 1
      CodeUri: src/
      Timeout: 120
      Runtime: python3.7
      Tracing: Active
      Environment:
        Variables:
          STORAGE_BUCKET: !Ref StorageBucket
          LEECH_BUCKET: !Ref LeechBucket
          ALGERNON_BUCKET_NAME: !Ref AlgernonBucket
  ExtractObjects:
    Type: AWS::Serverless::Function
    Properties:
      Handler: toll_booth.extract_credible_objects_h
      Role: !ImportValue dev-worker-role-arn
      ReservedConcurrentExecutions: 1
      CodeUri: src/
      Timeout: 240
      Runtime: python3.7
      Tracing: Active
      Environment:
        Variables:
          STORAGE_BUCKET: !Ref StorageBucket
          LEECH_BUCKET: !Ref LeechBucket
          ALGERNON_BUCKET_NAME: !Ref AlgernonBucket
  ParseExtractionBatch:
    Type: AWS::Serverless::Function
    Properties:
      Handler: toll_booth.parse_batch_encounters
      Role: !ImportValue dev-worker-role-arn
      ReservedConcurrentExecutions: 1
      CodeUri: src/
      Timeout: 900
      Runtime: python3.7
      Tracing: Active
      Environment:
        Variables:
          STORAGE_BUCKET: !Ref StorageBucket
          LEECH_BUCKET: !Ref LeechBucket
          ALGERNON_BUCKET_NAME: !Ref AlgernonBucket
