AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  functionality related to the Credible Behavioral Health Software platform

Parameters:
  IsDev:
    Type: String
    Default: 'False'
    AllowedValues:
      - 'False'
      - 'True'
  StorageBucket:
    Type: String
    Description: Location to store extracted Credible data
    Default: algernonsolutions-gentlemen-dev

Conditions:
  DevDeploy: !Equals [!Ref IsDev, 'True']
  ProdDeploy: !Equals [!Ref IsDev, 'False']

Resources:
  Task:
    Type: AWS::Serverless::Function
    Properties:
      Handler: toll_booth.tasks.handler
      Role: !ImportValue dev-worker-role-arn
      ReservedConcurrentExecutions: 1
      CodeUri: src/
      Timeout: 600
      Runtime: python3.7
      Tracing: Active
      Environment:
        Variables:
          STORAGE_BUCKET: !Ref StorageBucket
      Events:
        getClients:
          Type: SQS
          Properties:
            Queue: !GetAtt GetClients.Outputs.QueueArn
            BatchSize: 10
            Enabled: true
        getClientEncounters:
          Type: SQS
          Properties:
            Queue: !GetAtt GetClientEncounters.Outputs.QueueArn
            BatchSize: 10
            Enabled: true
        getClientEncounter:
          Type: SQS
          Properties:
            Queue: !GetAtt GetClientEncounter.Outputs.QueueArn
            BatchSize: 10
            Enabled: true
  GetClients:
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-east-1:726075243133:applications/AlgernonShuckLine
        SemanticVersion: 0.0.8
      Parameters:
        TaskName: "get_client_ids"
  GetClientEncounters:
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-east-1:726075243133:applications/AlgernonShuckLine
        SemanticVersion: 0.0.8
      Parameters:
        TaskName: "get_client_encounter_ids"
        DeadLetterArn: !GetAtt GetClients.Outputs.DeadLetterArn
        MasterKeyId: !GetAtt GetClients.Outputs.MasterKeyId
  GetClientEncounter:
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-east-1:726075243133:applications/AlgernonShuckLine
        SemanticVersion: 0.0.8
      Parameters:
        TaskName: "get_encounter"
        DeadLetterArn: !GetAtt GetClients.Outputs.DeadLetterArn
        MasterKeyId: !GetAtt GetClients.Outputs.MasterKeyId

Outputs:
  CredibleFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt Task.Arn
  GetClientsListener:
    Value: !GetAtt GetClients.Outputs.ListenerArn
  GetClientEncounters:
    Value: !GetAtt GetClientEncounters.Outputs.ListenerArn
  GetClientEncounter:
    Value: !GetAtt GetClientEncounter.Outputs.ListenerArn